### ISSUE TITLE
Issues in the install

### ISSUE THREAD

**Issue by russau** [trevorscott/edm-terraform#3]
First of all - thanks for creating this!  Posting this issue with the hopes someone else new to Heroku like me finds the fixes I needed to install this.

I saw this the first time I attempted to run thru the `terraform apply`.

> Did you mean auth:login? [y/n]: Waiting for Kafka Topics...
>  ›   Warning: kafka:topics is not a heroku command.

The fix was a simple as installing the plugin: `heroku plugins:install heroku-kafka`

Then I saw an error attempting to create the database tables.

> * heroku_addon.database: Error running command './setup-postgres.sh k1-edm-stats': exit status 1. Output: --> Connecting to postgresql-opaque-20376
>  ▸    The local psql command could not be located. For help installing psql, see
>  ▸    https://devcenter.heroku.com/articles/heroku-postgresql#local-setup

I didn't have the `psql` cli installed on my mac, I followed the instructions here to install: https://devcenter.heroku.com/articles/heroku-postgresql#set-up-postgres-on-mac

If you think this justifies a `README.md` update I can create a pull request.

Russ

**Comment by trevorscott** [comment]
Hi @russau, thank you for pointing this out! If you would like to update the README I would welcome a PR.

**Comment by trevorscott** [comment]
Hey @russau, thanks for your help in identifying how the set up documentation could be better. I went ahead and updated the README (https://github.com/heroku-examples/edm-terraform/commit/524a73e971903d124eca6da38b197474e414812a)  so that it clearly lists all the requirements and how to set each of them up. Hopefully this helps people have a better experience deploying this system in the future.

**Comment by russau** [comment]
Looks good :)
